name: 2025-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nb_conda_kernels
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - ipykernel         
  - ipywidgets
  - nbdime
  - arviz
  - emcee
  - ptemcee
  - zeus-mcmc
  - numdifftools
  - corner
  - scikit-learn
  - scikit-image
  - pydoe
  - gpy
  - gpyopt
  - pip
  - pip:
       - watermark
